CREATE TABLE purchase (
    id INT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(200) NOT NULL,
    color VARCHAR(30) NOT NULL,
    driveType VARCHAR(30) NOT NULL,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL,
    password VARCHAR(200) NOT NULL
);
CREATE TABLE files (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    type VARCHAR(200) NOT NULL,
    size INT NOT NULL,
    content LONGBLOB NOT NULL
);